#!/bin/bash

echo "🔧 Fix Xcode Build Error"
echo "======================="

echo ""
echo "📊 Bước 1: Kiểm tra Xcode project..."
if [ -f "SevenChat.xcodeproj/project.pbxproj" ]; then
    echo "✅ Xcode project found"
else
    echo "❌ Xcode project not found"
    exit 1
fi

echo ""
echo "📊 Bước 2: Clean build folder..."
rm -rf ~/Library/Developer/Xcode/DerivedData/SevenChat-*
echo "✅ Cleaned derived data"

echo ""
echo "📊 Bước 3: Kiểm tra Swift version..."
xcodebuild -version
swift --version

echo ""
echo "📊 Bước 4: Kiểm tra build configuration..."
echo "Scheme: SevenChat"
echo "Target: ElementX"
echo "Configuration: Release"

echo ""
echo "📊 Bước 5: Thử build với verbose output..."
echo "Hãy chạy lệnh sau trong Terminal:"
echo ""
echo "cd /Users/hieu/Downloads/element-x-ios"
echo "xcodebuild -scheme SevenChat -configuration Release -destination 'platform=iOS Simulator,name=iPhone 15' clean build"
echo ""
echo "Hoặc build cho device thật:"
echo "xcodebuild -scheme SevenChat -configuration Release -destination 'platform=iOS,id=YOUR_DEVICE_ID' clean build"
echo ""
echo "📱 Để lấy Device ID:"
echo "xcrun devicectl list devices"

echo ""
echo "🔍 CÁC LỖI THƯỜNG GẶP:"
echo ""
echo "1. **Swift version mismatch**:"
echo "   - Kiểm tra Swift version trong project settings"
echo "   - Đảm bảo Xcode version tương thích"
echo ""
echo "2. **Missing dependencies**:"
echo "   - Chạy: xcodebuild -resolvePackageDependencies"
echo "   - Kiểm tra Package.swift files"
echo ""
echo "3. **Code signing issues**:"
echo "   - Kiểm tra signing & capabilities"
echo "   - Đảm bảo provisioning profile hợp lệ"
echo ""
echo "4. **File permissions**:"
echo "   - Chạy: chmod +x scripts/*.sh"
echo "   - Kiểm tra file permissions"
echo ""
echo "5. **Generated files missing**:"
echo "   - Chạy: ./Tools/Scripts/generate.sh (nếu có)"
echo "   - Kiểm tra Generated/ folder"
echo ""
echo "📋 HÃY THỬ CÁC BƯỚC SAU:"
echo ""
echo "1. **Clean và rebuild**:"
echo "   - Product > Clean Build Folder"
echo "   - Product > Build"
echo ""
echo "2. **Reset Xcode**:"
echo "   - Quit Xcode"
echo "   - Xóa DerivedData: rm -rf ~/Library/Developer/Xcode/DerivedData"
echo "   - Mở lại Xcode"
echo ""
echo "3. **Kiểm tra Swift files**:"
echo "   - Tìm syntax errors trong Swift files"
echo "   - Kiểm tra missing imports"
echo ""
echo "4. **Kiểm tra dependencies**:"
echo "   - File > Packages > Reset Package Caches"
echo "   - File > Packages > Resolve Package Versions"
echo ""
echo "Hãy cho tôi biết lỗi chi tiết từ Xcode để tôi có thể giúp sửa cụ thể!"
