#!/bin/bash

echo "🧪 TEST AD HOC DISTRIBUTION"
echo "============================"

echo ""
echo "📋 HƯỚNG DẪN BUILD AD HOC:"
echo "=========================="
echo "1. Mở Xcode"
echo "2. Chọn scheme 'SevenChat'"
echo "3. Chọn 'Any iOS Device' hoặc device thật"
echo "4. Product > Archive"
echo "5. Distribute App > Ad Hoc"
echo "6. Cài app lên iPhone"
echo ""

echo "📋 HƯỚNG DẪN TEST:"
echo "=================="
echo "1. Mở app SevenChat trên iPhone"
echo "2. Đăng nhập vào tài khoản"
echo "3. Đợi 10-30 giây để app đăng ký device token"
echo "4. Kiểm tra logs trong Console app:"
echo "   - Tìm: 🚨 [AppCoordinator] 🔧 FORCE: Triggering device token registration"
echo "   - Tìm: 🚨 [AppCoordinator] 🎫 Received device token from APNS"
echo "   - Tìm: 🚨 SUCCESS: Device token registered with Matrix server!"
echo "5. Gửi tin nhắn thật từ tài khoản khác"
echo "6. Kiểm tra notification và badge count"
echo ""

echo "🔍 KIỂM TRA SAU KHI ĐĂNG NHẬP:"
echo "=============================="
echo "Chạy lệnh sau để kiểm tra device token:"
echo ""
echo "ssh root@178.16.137.171 \"docker exec synapse-db psql -U synapse -d synapse -c \\\"SELECT pushkey, app_id, profile_tag, kind FROM pushers WHERE app_id = 'io.sevenchat.sevenchat';\\\"\""
echo ""

echo "🧪 TEST PUSH NOTIFICATION:"
echo "=========================="
echo "Sau khi có device token, chạy:"
echo ""
echo "chmod +x test_final_push.sh && ./test_final_push.sh"
echo ""

echo "🎯 KẾT QUẢ MONG ĐỢI:"
echo "==================="
echo "✅ Device token được đăng ký với Matrix server"
echo "✅ Push notification hoạt động với Production APNS"
echo "✅ Badge count tăng khi có tin nhắn mới"
echo "✅ Notification hiển thị đúng format"
echo ""

echo "📱 LƯU Ý QUAN TRỌNG:"
echo "==================="
echo "1. Ad Hoc Distribution sử dụng Production APNS"
echo "2. Device token sẽ khác với Development build"
echo "3. Cần đăng ký device UDID trong Apple Developer"
echo "4. Provisioning profile phải bao gồm device UDID"
echo ""

echo "✅ Sẵn sàng test Ad Hoc Distribution!"
